#This plugin was developed by Auties
#Do you want a similar one? Contact me on Spigot or on Telegram (Alex0589 | @Auties)
#You are not allowed to claim this plugin as yours
#You can decompile this plugin just for Educational purpose
#You are not allowed to claim my code as yours
#------------------------------------------------------- METEOR SHARD --------------------------------------------------------------------
Plugin-Enabled: false


